from time import sleep


def clear_output():
    for i in range(100):
        print("\n")


clear_output()
print(" you enter a office cubical that seems oddly familiar. a bot floats up to you.")
print("'hello welcome to a acurate simulation of OFFICE WORKER. take a slip and start the day.'")
print(" you look around and see and number of odd things. will you")
print("1: throw some thing at job bot.")
print("2: take a work slip")
print("3:take a work slip and throw it at job bot")
print("4: exit")
print("------------------------------------------------------------------------------------------------")
answer = input()
while True:
    if answer == "1":
        clear_output()
        print("you threw a stapler at job bot.")  # find out how to fix this one
        print("sparks flew from it.")
        print("1: exit")
        print("--------------------------------------------------------------------------------------------")
        answer = input()
        if answer == "1":
            clear_output()
            continue
    elif answer == "2":
        clear_output()
        print("you start your job")
        print("a floating cart goes up to your cubical")
        print("with a box of doughnuts and three coffee mugs.")
        print("'a human worker would usually start their day with a brown liquid stimulant.'")
        print("a board appears across from your cubical displaying a few images.")
        print("'follow the board for instructions'")
        print("1: pour yourself some coffee")
        print("2: throw a coffee mug at job bot")
        print("3: pour yourself some coffee and drink it and throw the coffee mug at job bot")
        print("4: exit")
        print("---------------------------------------------------------------------------------------------")
        answer = input()
    elif answer == "3":
        clear_output()
        print("you start your job by throwing the slip at job bot")
        print("'ow' sparks fly from job bot.")
        print("a floating cart goes up to your cubical")
        print("with a box of doughnuts and three coffee mugs.")
        print("'a human worker would usually start their day with a brown liquid stimulant.'")
        print("a board appears across from your cubical displaying a few images.")
        print("'follow the board for instructions'")
        print("1: pour yourself some coffee")
        print("2: throw a coffee mug at job bot")
        print("3: pour yourself some coffee and drink it and throw the coffee mug at job bot")
        print("4: exit")
        print("-------------------------------------------------------------------------------------------------")
        answer = input()
    if answer == "1":
        clear_output()
        sleep(3)
        print("you drink your coffee and as you drink the coffee the board images change")
        print("1: continue job")
        print("---------------------------------------------------------------------------------------------")
        answer = input()
        answer = "2"
    elif answer == "2":
        clear_output()
        print("you throw a mug at job bot.")
        print("sparks fly from the bot.")
        print("1: continue job")
        print("---------------------------------------------------------------------------------------------")
        answer = input()
        answer = "2"
    if answer == "3":
        clear_output()
        print("you drink you coffee and as you finish you here a ding from the board.")
        print("then you throw the coffee mug at job bot.")
        print(
            "'good. humans would also often indulge in treats called DOUGHNUTS. take a DOUGHNUT and lets get moving.'")
        print("1: open the box and eat a doughnut")
        print("2: open the box and throw a doughnut at job bot")
        print("3: eat a doughnut then throw one at job bot")
        print("4: exit")
        print("---------------------------------------------------------------------------------------------")
        answer = input()
    if answer == "1":
        clear_output()
        print("you open the box and there is a small assortment of doughnuts.")
        print("you chose the doughnut with blue frosting and sprinkles and eat it.")
        print("the board dings as the images fly of the screen.")
        sleep(5)
        clear_output()
        print("JOB COMPLETE")
        sleep(3)
        clear_output()
        print("'good now take a slip and lets start another job'")
        print("another job slip prints from the slot at the end of your desk")
        print("1: take a slip and throw at at job bot")
        print("2: take a slip")
        print("3: throw something at job bot")
        print("4: exit")
        print("----------------------------------------------------------------------------------------------")
        answer = input()
    elif answer == "2":
        print("you throw a doughnut at job bot")
        print("and the sparks fly.")
        print("1: back to job")
        answer = input()
        answer = "3"
    if answer == "3":
        clear_output()
        print("you open the box and there is a small assortment of doughnuts.")
        print("you pick up a doughnut then throw it at job bot and sparks fly from the bot.")
        print("you chose the doughnut with blue frosting and sprinkles and eat it.")
        print("the board dings as the images fly of the screen.")
        sleep(5)
        clear_output()
        print("JOB COMPLETE")
        sleep(3)
        clear_output()
        print("'good now take a slip and lets start another job'")
        print("another job slip prints from the slot at the end of your desk")
        print("1: take a slip and throw at at job bot")
        print("2: take a slip")
        print("3: throw something at job bot")
        print("4: exit")
        print("----------------------------------------------------------------------------------------------")
        answer = input()
    if answer == "1":
        clear_output()
        print("you take the job slip and start you next job.")
        print("'now it is time for you to use COMPUTER'")
        print("'turn on the tower and lets get started.'")
        print("1: attempt to turn on the computer and the tower")
        print("2: hit the tower in hopes it turns on.")
        print("3: check to make sure the computer and the tower is plugged in")
        print("4: exit")
    if answer == "4":
        break
clear_output()
print("come bock soon.")
sleep(3)
clear_output()